name: vocab_elevate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  csv: ^5.0.0

  flutter_local_notifications: ^19.2.0
  flutter_local_notifications_linux: ^6.0.0
  android_intent_plus: ^5.3.0
  device_info_plus: ^11.3.0
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/data/VOCAB_AR.csv
